# coding: utf-8

"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.shift_agent import ShiftAgent

class TestShiftAgent(unittest.TestCase):
    """ShiftAgent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShiftAgent:
        """Test ShiftAgent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShiftAgent`
        """
        model = ShiftAgent()
        if include_optional:
            return ShiftAgent(
                id = 56,
                agent_name = '',
                agent_id = '',
                shift_status = 'online',
                shift_start_time = '',
                shift_end_time = '',
                communication_channels = 'unknown',
                email = '',
                operator_id = '',
                department_ids = [
                    56
                    ]
            )
        else:
            return ShiftAgent(
        )
        """

    def testShiftAgent(self):
        """Test ShiftAgent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
