# coding: utf-8

"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agent_metrics_client.api.online_agents_api import OnlineAgentsApi


class TestOnlineAgentsApi(unittest.TestCase):
    """OnlineAgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OnlineAgentsApi()

    def tearDown(self) -> None:
        pass

    def test_online_agents_list(self) -> None:
        """Test case for online_agents_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
