# coding: utf-8

"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.csat_api import CsatApi


class TestCsatApi(unittest.TestCase):
    """CsatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CsatApi()

    def tearDown(self) -> None:
        pass

    def test_csat_save_create(self) -> None:
        """Test case for csat_save_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
