# coding: utf-8

"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.sample_api import SampleApi


class TestSampleApi(unittest.TestCase):
    """SampleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SampleApi()

    def tearDown(self) -> None:
        pass

    def test_sample_save_create(self) -> None:
        """Test case for sample_save_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
