# coding: utf-8

# flake8: noqa
"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.shift_agent import ShiftAgent
