# coding: utf-8

# flake8: noqa

"""
    Agent Metrics API

    API for online agents

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CsatApi",
    "MetricsApi",
    "OnlineAgentsApi",
    "SampleApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ShiftAgent",
]

# import apis into sdk package
from openapi_client.api.csat_api import CsatApi as CsatApi
from openapi_client.api.metrics_api import MetricsApi as MetricsApi
from openapi_client.api.online_agents_api import OnlineAgentsApi as OnlineAgentsApi
from openapi_client.api.sample_api import SampleApi as SampleApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.shift_agent import ShiftAgent as ShiftAgent
